spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testPharma
    username: root
    password: root
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  level:
    org.zalando.logbook: trace
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration